title: AI Conference Deadlines
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Ge Yang

url: "https://fortyfive-ai.github.io"
baseurl: "/ai-deadlines"

twitter_hashtag: episodeyang
github_username: fortyfive-ai
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
