title: AI Conference Deadlines
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Ge Yang

url: "https://aideadlin.es"
baseurl: ""

twitter_hashtag: episodeyang
github_username: geyang
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
